name: Mirror to Codeberg

on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Mirror to Codeberg
        uses: cssnr/mirror-repository-action@2af5bf347684245f52b5f56502956a57f9b8813e # v1
        with:
          host: https://codeberg.org
          username: thedavidweng
          password: ${{ secrets.CODEBERG_TOKEN }}
