name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: thedavidweng/cli-workflow-template/.github/workflows/go-release.yml@main
    secrets: inherit
